name: progetto_dd
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.0.9
  firebase_database: ^10.4.10
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.8.0
  rxdart: ^0.27.7
  math_expressions: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/strings.json